/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.hw5;

public class App {

  public static void main(String[] args) {

    Person person = new Person();
    person.isPassengerHungry();

  }
}
