/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.hw6;

import java.util.Scanner;

public class App {

  public String promptUser(String prompt) {
    Scanner scanner = new Scanner(System.in);
    System.out.print(prompt);
    String input = scanner.nextLine();
    System.out.println("You entered: " + input);
    // return scanner.nextLine();
    return input;
  }

  public static void main(String[] args) {

    App app = new App();
    String name = app.promptUser("What is your name? ");
    System.out.println("Hello, " + name + ", nice to meet you!");

  }
}
