/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.hw6;

import java.io.FileReader;

public class App {

  public static void main(String[] args) {

    FileReader fr = null;
    try {
      // dangereous code here
      fr = new FileReader("test.txt");

    } catch (Exception e) {
      e.printStackTrace();
      // more dangerous code here
    } finally {
      if (fr != null) {
        try {
          fr.close();
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
    }
  }
}
