/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.ch10;

public class App {

  public void startVehicle(Vehicle vehicle) {
    vehicle.start();
  }

  public static void main(String[] args) {

    App app = new App();

    Honda honda = new Honda(1234);

    app.startVehicle(honda);

    MyCoolHonda myCoolHonda = new MyCoolHonda(5678);

    int compare = myCoolHonda.compareTo(myCoolHonda);
    System.out.println("compare: " + compare);

  }
}
