/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.ch12;

import java.io.File;

public class App {

  public static void main(String[] args) {
    File file = new File("bin/main");
    System.out.println(file.getAbsolutePath());
    String[] files = file.list();
    for (String f : files) {
      System.out.println(f);
      while (new File(file.getAbsolutePath() + "/" + f).isDirectory()) {
        String[] subFiles = new File(file.getAbsolutePath() + "/" + f).list();
        for (String sf : subFiles) {
          System.out.println("  " + sf);
        }
        break;
      }
    }
  }
}
