/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.ch9;

public class App {

  public void driveCar(Car car) {
    car.drive();
  }

  public void honkHorn(Car car) {
    car.honkHorn();
  }

  public void printCarDetails(Car car) {
    System.out.println("Number of doors: " + car.getNumberOfDoors());
    System.out.println("Is electric: " + car.getIsElectric());
    System.out.println("Color: " + car.getColor());
  }

  public static void main(String[] args) {

    App app = new App();

    // abstract class demo
    // we cannot create an instance of an abstract class
    // Car car = new Car();

    // however, we can create an instance of a class that extends an abstract class
    Honda honda = new Honda();
    honda.setColor("green");

    // we can call the methods of the abstract class
    System.out.println("Number of doors: " + honda.getNumberOfDoors());

    Mercedes mercedes = new Mercedes();
    mercedes.setColor("black");

    app.printCarDetails(honda);
    app.driveCar(honda);
    app.honkHorn(honda);

    app.printCarDetails(mercedes);
    app.driveCar(mercedes);
    app.honkHorn(mercedes);
  }
}
