/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.ch9;

public class App {

  public static void main(String[] args) {

    MyArrayList list = new MyArrayList(2);
    list.add(new Box(1, 2, 3));
    System.out.println("list.size(): " + list.size());
    list.add(new Box(4, 5, 6));
    System.out.println("list.size(): " + list.size());
    list.add(new Box(7, 8, 9));
    System.out.println("list.size(): " + list.size());

    MyArrayList list2 = new MyArrayList(2);
    list2.addAll(list);

    list2.removeAll();
    for (int i = 0; i < list2.size(); i++) {
      System.out.println(list2.get(i));
    }
    System.out.println("list2.size(): " + list2.size());
  }
}
