/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.sorting;

public class App {

  public void swap(int[] arr, int i, int j) {
    int temp = arr[i];
    arr[i] = arr[j];
    arr[j] = temp;
  }

  public void insertionSort(int[] arr) {
    for (int i = 1; i < arr.length; i++) {
      System.out.println("outer loop: " + i);
      int j = i - 1;
      int temp = arr[i];
      while ((j >= 0) && (arr[j] > temp)) {
        arr[j + 1] = arr[j]; // shift element rightward to make room
        j--;
      }
      arr[j + 1] = temp; // insert value in proper location

      printArray(arr);
    }
  }

  public void selectionSort(int[] arr) {
    for (int i = 0; i < arr.length - 1; i++) {
      System.out.println("outer loop: " + i);
      int minIndex = i;
      for (int j = i + 1; j < arr.length; j++) {
        System.out.println("inner loop: " + j);
        if (arr[j] < arr[minIndex]) { // find minimum from i+1 to end of array
          minIndex = j;
        }
      }
      swap(arr, i, minIndex); // swap arr[i] with arr[minIndex]
      printArray(arr);
    }
  }

  public void bubbleSort(int[] arr) {
    // we are going to assume that the array is not sorted
    boolean isSorted = false;
    int loopCount = 0;

    while (!isSorted) { // returns true if isSorted is false (keep going until sorted)
      isSorted = true; // will not re-enter while loop unless a swap is done

      System.out.println("Loop count: " + loopCount++);

      for (int j = 0; j < arr.length - 1; j++) {
        if (arr[j] > arr[j + 1]) { // compare side by side
          swap(arr, j, j + 1); // swap j with j+1
          isSorted = false; // force loop re-entry of outer loop

          printArray(arr);
        }
      }
    }
  }

  public void printArray(int[] arr) {
    System.out.print("[");
    for (int i = 0; i < arr.length; i++) {
      System.out.print(arr[i]);
    }
    System.out.println("]");
  }

  public static void main(String[] args) {

    App app = new App();
    int[] arr = {5, 3, 2, 4, 1};
    app.printArray(arr);
    // app.bubbleSort(arr);
    // app.selectionSort(arr);
    app.insertionSort(arr);
    System.out.println("Sorted array:");
    app.printArray(arr);


  }
}
