/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.project1;

public class App {

  public static void main(String[] args) {

    // if the length of the array is 3, the indexes are from 0 to 2
    Toy[] toys = new Toy[3];
    toys[0] = new Toy("Lego", 29.99);
    toys[1] = new Toy("Hot Wheels", 9.99);
    toys[2] = new Toy("Nerf", 19.99);
    // in the array above, you can 3 toys with the following indexes:
    // 1. toys[0]
    // 2. toys[1]
    // 3. toys[2] // then I will be placing the toy here at this index
    ToyStore store = new ToyStore("Toys R Us");

    store.addToy(new Toy("Barbie", 19.99));
    store.addToy(new Toy("GI Joe", 19.99));
    store.addToy(new Toy("Transformers", 29.99));

    store.addToys(toys);
  }
}
